- name: Create temporary file to store the constraints
  ansible.builtin.tempfile:
    path: /home/ubuntu/
    prefix: "constraints."
    suffix: ".txt"
  register: constraints_file

- name: GET the constraints file
  get_url:
    url: "{{ pip_constraints_url }}"
    dest: "{{ constraints_file.path }}"
    mode: 0444
    force: true
  when: constraints_file is defined and pip_constraints_url is defined and pip_constraints_url is not none and pip_constraints_url|length > 0

- name: Get stat of temporary constraints file
  ansible.builtin.stat:
    path: "{{ constraints_file.path }}"
  register: constraints_stat

- name: Record file location
  set_fact:
    tox_constraints_env:
      TEST_CONSTRAINTS_FILE: "{{ constraints_file.path }}"
  when: constraints_stat.stat.exists and constraints_stat.stat.size > 0
